encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 5
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author: 
  name: Poplar
  email: somanywf@sina.com
  link: http://yangedu.github.io/
  weibo: http://weibo.com/u/1640376507
  github: https://github.com/yangedu
  github_username:  yangedu
  weibo_username:  somanywf

# 站点信息
title : 聚木成林
description: 
  码农待开发...
url: http://yangedu.github.io/
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.png

# disqus 设置
#disqus:
#  shortname: w-poplar

#profile 个人信息

profile_desc : 人没有牺牲就什么都得不到<br />为了得到什么东西<br />就需要付出同等的代价...<br />这就是炼金术“等价交换”的原理...<br />那时的我们，</br>相信那就是世界的真实...<br />——《钢之炼金术士》

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章
